// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Engine-specific options chosen when the download was added.
 */
export type EngineOptions = { 
/**
 * yt-dlp format selector (e.g. `137+140` or `bestaudio`).
 */
formatId?: string, 
/**
 * Extract audio only (requires FFmpeg for conversion).
 */
audioOnly: boolean, 
/**
 * Torrent: indexes of the files to download (None = all).
 */
torrentFiles?: Array<number>, 
/**
 * HTTP: requested number of connections (None = use settings).
 */
connections?: number, };
