// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A ready-made choice for the UI (best, 1080p, audio only, …).
 */
export type FormatPreset = { 
/**
 * yt-dlp format selector.
 */
selector: string, label: string, height: number | null, audioOnly: boolean, approxSize: number | null, };
