//! Video engine tests with the real yt-dlp binary against a locally served
//! clip generated by FFmpeg. Skipped (with a message) when the tools are missing.

mod common;

use std::process::Command;

use common::*;
use pixidl_core::manager::AddSource;
use pixidl_core::types::*;

fn have(bin: &str, arg: &str) -> bool {
    Command::new(bin).arg(arg).output().map(|o| o.status.success()).unwrap_or(false)
}

async fn serve_dir(dir: std::path::PathBuf) -> std::net::SocketAddr {
    let app = axum::Router::new()
        .nest_service("/media", tower_http::services::ServeDir::new(dir))
        .route("/page", axum::routing::get(|| async { ([("content-type", "text/html")], "<html><body>No media here</body></html>") }));
    let l = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let addr = l.local_addr().unwrap();
    tokio::spawn(async move { axum::serve(l, app).await.unwrap() });
    addr
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn ytdlp_inspect_and_download() {
    if !have("yt-dlp", "--version") || !have("ffmpeg", "-version") {
        eprintln!("SKIPPED: yt-dlp and ffmpeg are required for this test");
        return;
    }
    let media = tempfile::tempdir().unwrap();
    let clip = media.path().join("clip.mp4");
    let ok = Command::new("ffmpeg")
        .args(["-hide_banner", "-loglevel", "error", "-f", "lavfi", "-i", "testsrc=duration=3:size=320x240:rate=25", "-f", "lavfi", "-i", "sine=frequency=440:duration=3", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest", "-y"])
        .arg(&clip)
        .status()
        .unwrap()
        .success();
    assert!(ok, "ffmpeg could not generate the test clip");
    let addr = serve_dir(media.path().to_path_buf()).await;
    let url = format!("http://{addr}/media/clip.mp4");

    let h = harness_with(|_| {}).await;
    let (ytdlp, ffmpeg, _torrent) = h.mgr.engine_status().await;
    assert!(ytdlp.available && ytdlp.version.is_some(), "{ytdlp:?}");
    assert!(ffmpeg.available, "{ffmpeg:?}");

    let insp = h.mgr.inspect_url(&url, Some(EngineKind::Video)).await.unwrap();
    assert!(insp.warning.is_none(), "{:?}", insp.warning);
    let info = insp.video.expect("video metadata");
    assert_eq!(info.title, "clip");
    assert!(!info.formats.is_empty());
    assert!(!info.presets.is_empty());

    let d = h
        .mgr
        .add(
            AddDownloadRequest {
                url: url.clone(),
                engine: Some(EngineKind::Video),
                engine_options: EngineOptions { format_id: Some(info.presets[0].selector.clone()), ..Default::default() },
                ..Default::default()
            },
            AddSource::User,
        )
        .await
        .unwrap();
    assert_eq!(d.category, "Videos");
    let done = h.wait_status(&d.id, DownloadStatus::Completed, 60).await;
    assert!(done.filename.starts_with("clip"), "{}", done.filename);
    let out = h.dir.path().join(&done.filename);
    assert!(out.exists());
    assert_eq!(std::fs::metadata(&out).unwrap().len(), std::fs::metadata(&clip).unwrap().len());
    assert_eq!(done.downloaded_bytes, std::fs::metadata(&out).unwrap().len());
    assert!(!h.dir.path().join(".pixidl-partial").exists(), "temp folder cleaned up");
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn ytdlp_errors_are_reported() {
    if !have("yt-dlp", "--version") {
        eprintln!("SKIPPED: yt-dlp is required for this test");
        return;
    }
    let empty = tempfile::tempdir().unwrap();
    let addr = serve_dir(empty.path().to_path_buf()).await;
    let h = harness_with(|_| {}).await;
    let insp = h.mgr.inspect_url(&format!("http://{addr}/page"), Some(EngineKind::Video)).await.unwrap();
    let w = insp.warning.expect("extractor error surfaced");
    assert_eq!(w.kind, ErrorKind::ExtractorFailed);
    assert!(w.detail.is_some());

    // A page with no media auto-detected as plain HTTP (no video upgrade).
    let insp = h.mgr.inspect_url(&format!("http://{addr}/page"), None).await.unwrap();
    assert_eq!(insp.engine, EngineKind::Http);

    let d = h
        .mgr
        .add(AddDownloadRequest { url: format!("http://{addr}/page"), engine: Some(EngineKind::Video), ..Default::default() }, AddSource::User)
        .await
        .unwrap();
    let f = h.wait_status(&d.id, DownloadStatus::Failed, 60).await;
    assert_eq!(f.error_kind, Some(ErrorKind::ExtractorFailed));
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn missing_extractor_is_reported_as_engine_unavailable() {
    let tools = pixidl_core::tools::ToolLocator::without_system_path(vec![]);
    let engine = pixidl_core::engines::video::VideoEngine::new(std::sync::Arc::new(tools));
    let r = engine.inspect("https://example.com/v", "/definitely/not/here", "").await;
    assert_eq!(r.unwrap_err().kind, ErrorKind::EngineUnavailable);
}
