#!/usr/bin/env node
// Builds the pixidl browser extension for Chromium browsers and Firefox.
//
//   node browser-extension/build.mjs
//
// Inputs:  src/ (pages, scripts, icons, _locales) + manifest.base.json
// Outputs: dist/chromium/            unpacked extension (Chrome, Edge, Brave, Opera, Vivaldi)
//          dist/firefox/             unpacked add-on (Firefox 128+)
//          dist/pixidl-chromium.zip  the same files, zipped
//          dist/pixidl-firefox.xpi   the same files, zipped
//
// No npm dependencies (Node 22+). The output is deterministic: files are
// written in sorted order and every ZIP entry carries the same timestamp.

import { mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import zlib from "node:zlib";

const HERE = dirname(fileURLToPath(import.meta.url));

export const FIREFOX_ID = "pixidl@pixidl.app";
export const FIREFOX_MIN_VERSION = "128.0";
export const CHROMIUM_MIN_VERSION = "116";
export const TARGETS = Object.freeze(["chromium", "firefox"]);

/** Files in src/ that are not copied as-is (content.js is bundled with lib.js). */
const BUNDLED = new Set(["content.js"]);

// ---- Manifest ------------------------------------------------------------------

/** The manifest for one target, derived from manifest.base.json. */
export function generateManifest(base, target) {
  if (!TARGETS.includes(target)) throw new Error(`unknown target: ${target}`);
  const manifest = structuredClone(base);
  delete manifest.background;
  delete manifest.browser_specific_settings;
  if (target === "chromium") {
    if (typeof manifest.key !== "string" || !manifest.key) throw new Error("manifest.base.json must contain the Chromium key");
    manifest.background = { service_worker: "background.js", type: "module" };
    manifest.minimum_chrome_version = CHROMIUM_MIN_VERSION;
  } else {
    delete manifest.key;
    delete manifest.minimum_chrome_version;
    manifest.background = { scripts: ["background.js"], type: "module" };
    manifest.browser_specific_settings = {
      gecko: {
        id: FIREFOX_ID,
        strict_min_version: FIREFOX_MIN_VERSION,
        data_collection_permissions: { required: ["none"] },
      },
    };
  }
  return manifest;
}

// ---- Content script bundle -------------------------------------------------------

/**
 * The classic content script: lib.js (with its `export` keywords removed)
 * followed by content.js, inside one IIFE so nothing leaks into the page's
 * isolated world as globals.
 */
export function bundleContentScript(libSource, contentSource) {
  if (/^\s*import\b/m.test(libSource)) throw new Error("lib.js must not import anything (it is inlined into the content script)");
  const lib = libSource.replace(/^export (?=(?:async\s+)?function\b|const\b|let\b|class\b)/gm, "");
  if (/^\s*export\b/m.test(lib)) throw new Error("lib.js uses an export form the bundler does not support");
  if (/^\s*(import|export)\b/m.test(contentSource)) throw new Error("content.js must be a classic script");
  return [
    "// Generated by build.mjs from src/lib.js and src/content.js. Do not edit.",
    "(() => {",
    '"use strict";',
    lib.trimEnd(),
    "",
    contentSource.trimEnd(),
    "})();",
    "",
  ].join("\n");
}

// ---- ZIP writer ------------------------------------------------------------------

// 2026-01-01 00:00:00 in MS-DOS format, used for every entry.
const DOS_TIME = 0;
const DOS_DATE = ((2026 - 1980) << 9) | (1 << 5) | 1;

/**
 * A ZIP archive (deflate or store, whichever is smaller) of
 * `[{name, data: Buffer}]`. Names use forward slashes; entries keep the given order.
 */
export function createZip(entries) {
  if (typeof zlib.crc32 !== "function") throw new Error("Node 22.2 or newer is required (zlib.crc32)");
  const locals = [];
  const centrals = [];
  let offset = 0;
  for (const { name, data } of entries) {
    if (!name || name.includes("\\") || name.startsWith("/") || name.split("/").includes("..")) throw new Error(`bad zip entry name: ${name}`);
    const nameBytes = Buffer.from(name, "utf8");
    const crc = zlib.crc32(data) >>> 0;
    const deflated = zlib.deflateRawSync(data, { level: 9 });
    const useDeflate = deflated.length < data.length;
    const body = useDeflate ? deflated : data;
    const method = useDeflate ? 8 : 0;

    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4); // version needed
    local.writeUInt16LE(0x0800, 6); // UTF-8 names
    local.writeUInt16LE(method, 8);
    local.writeUInt16LE(DOS_TIME, 10);
    local.writeUInt16LE(DOS_DATE, 12);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(body.length, 18);
    local.writeUInt32LE(data.length, 22);
    local.writeUInt16LE(nameBytes.length, 26);
    local.writeUInt16LE(0, 28);
    locals.push(local, nameBytes, body);

    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt16LE(0x0314, 4); // made by: Unix, spec 2.0
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(0x0800, 8);
    central.writeUInt16LE(method, 10);
    central.writeUInt16LE(DOS_TIME, 12);
    central.writeUInt16LE(DOS_DATE, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(body.length, 20);
    central.writeUInt32LE(data.length, 24);
    central.writeUInt16LE(nameBytes.length, 28);
    central.writeUInt16LE(0, 30); // extra
    central.writeUInt16LE(0, 32); // comment
    central.writeUInt16LE(0, 34); // disk
    central.writeUInt16LE(0, 36); // internal attributes
    central.writeUInt32LE((0o100644 << 16) >>> 0, 38); // -rw-r--r--
    central.writeUInt32LE(offset, 42);
    centrals.push(central, nameBytes);

    offset += local.length + nameBytes.length + body.length;
  }
  const centralSize = centrals.reduce((n, b) => n + b.length, 0);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(centralSize, 12);
  end.writeUInt32LE(offset, 16);
  return Buffer.concat([...locals, ...centrals, end]);
}

// ---- Build ---------------------------------------------------------------------

function listFiles(dir) {
  const out = [];
  const walk = (current) => {
    for (const name of readdirSync(current).sort()) {
      if (name.startsWith(".")) continue;
      const full = join(current, name);
      if (statSync(full).isDirectory()) walk(full);
      else out.push(relative(dir, full).split(sep).join("/"));
    }
  };
  walk(dir);
  return out;
}

/** The files of one target as `[{name, data}]`, sorted by name. */
export function targetFiles(target, { root = HERE } = {}) {
  const srcDir = join(root, "src");
  const base = JSON.parse(readFileSync(join(root, "manifest.base.json"), "utf8"));
  const files = new Map();
  for (const name of listFiles(srcDir)) {
    if (BUNDLED.has(name)) continue;
    files.set(name, readFileSync(join(srcDir, name)));
  }
  const content = bundleContentScript(readFileSync(join(srcDir, "lib.js"), "utf8"), readFileSync(join(srcDir, "content.js"), "utf8"));
  files.set("content.js", Buffer.from(content, "utf8"));
  files.set("manifest.json", Buffer.from(`${JSON.stringify(generateManifest(base, target), null, 2)}\n`, "utf8"));
  return [...files.keys()].sort().map((name) => ({ name, data: files.get(name) }));
}

/** Builds both targets into `outDir`; returns the output paths. */
export function build({ root = HERE, outDir = join(root, "dist") } = {}) {
  const outputs = {};
  mkdirSync(outDir, { recursive: true });
  for (const target of TARGETS) {
    const files = targetFiles(target, { root });
    const dir = join(outDir, target);
    rmSync(dir, { recursive: true, force: true });
    for (const { name, data } of files) {
      const path = join(dir, ...name.split("/"));
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, data);
    }
    const archive = join(outDir, target === "chromium" ? "pixidl-chromium.zip" : "pixidl-firefox.xpi");
    writeFileSync(archive, createZip(files));
    outputs[target] = { dir, archive, files: files.length };
  }
  return outputs;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const outputs = build();
  for (const [target, { dir, archive, files }] of Object.entries(outputs)) {
    console.log(`${target.padEnd(8)} ${files} files`);
    console.log(`  unpacked: ${dir}`);
    console.log(`  package:  ${archive}`);
  }
}
