// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineKind } from "./EngineKind";
import type { EngineOptions } from "./EngineOptions";
import type { Priority } from "./Priority";

/**
 * Request to add a download (from UI or browser extension).
 */
export type AddDownloadRequest = { url: string, filename?: string, 
/**
 * Destination directory. Must be inside an approved download directory.
 */
saveDir?: string, category?: string, priority?: Priority, 
/**
 * Engine override; `None` = use detector.
 */
engine?: EngineKind, referrer?: string, engineOptions: EngineOptions, 
/**
 * Start paused instead of queueing.
 */
startPaused: boolean, 
/**
 * ISO-8601 timestamp; the queue will not start the download earlier.
 */
scheduledAt?: string, 
/**
 * Raw .torrent file content (base64) when adding a torrent file.
 */
torrentBase64?: string, };
