// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadStatus } from "./DownloadStatus";
import type { EngineKind } from "./EngineKind";
import type { EngineOptions } from "./EngineOptions";
import type { ErrorKind } from "./ErrorKind";
import type { Priority } from "./Priority";

/**
 * One persisted download.
 */
export type Download = { id: string, 
/**
 * The URL actually downloaded (after normalisation / redirects).
 */
url: string, 
/**
 * The URL as supplied by the user or browser.
 */
originalUrl: string, referrer: string | null, filename: string, 
/**
 * Directory the file is saved into.
 */
saveDir: string, category: string, engine: EngineKind, status: DownloadStatus, priority: Priority, queuePosition: bigint, totalBytes: number | null, downloadedBytes: number, speedBps: number, uploadBps: number, etaSeconds: number | null, 
/**
 * Whether the server/engine supports resuming. `None` = not yet known.
 */
resumable: boolean | null, 
/**
 * Per-download speed limit in bytes/s (`None` = unlimited).
 */
speedLimitBps: number | null, connections: number, errorKind: ErrorKind | null, errorMessage: string | null, errorDetail: string | null, retryCount: number, engineOptions: EngineOptions, 
/**
 * Torrent peers (live, total seen) — only real engine values.
 */
peers: number | null, seeds: number | null, infoHash: string | null, title: string | null, thumbnail: string | null, createdAt: string, startedAt: string | null, completedAt: string | null, updatedAt: string, scheduledAt: string | null, 
/**
 * Set when a completed download's file can no longer be found on disk.
 */
fileMissing: boolean, };
