// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Global transfer statistics for the status bar / tray.
 */
export type GlobalStats = { total: number, active: number, queued: number, completed: number, failed: number, downloadBps: number, uploadBps: number, };
