// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";

export type InspectionError = { kind: ErrorKind, message: string, detail: string | null, };
