// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Download } from "./Download";
import type { EngineKind } from "./EngineKind";
import type { ProgressUpdate } from "./ProgressUpdate";

/**
 * Events emitted by the manager. The Tauri shell forwards them to the UI.
 */
export type ManagerEvent = { "type": "download_created", download: Download, } | { "type": "download_updated", download: Download, } | { "type": "download_progress", updates: Array<ProgressUpdate>, } | { "type": "download_completed", download: Download, } | { "type": "download_failed", download: Download, } | { "type": "download_removed", id: string, } | { "type": "queue_finished" } | { "type": "engine_error", engine: EngineKind, message: string, };
