// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TorrentEngineStatus = { running: boolean, listenPort: number | null, dhtEnabled: boolean, torrents: number, library: string, };
