// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineKind } from "./EngineKind";
import type { InspectionError } from "./InspectionError";
import type { TorrentInfo } from "./TorrentInfo";
import type { VideoInfo } from "./VideoInfo";

/**
 * Everything the Add dialog needs to know about a URL.
 */
export type UrlInspection = { url: string, finalUrl: string | null, engine: EngineKind, 
/**
 * Other engines that can reasonably be tried.
 */
alternatives: Array<EngineKind>, filename: string | null, totalBytes: number | null, contentType: string | null, resumable: boolean | null, category: string, video: VideoInfo | null, torrent: TorrentInfo | null, 
/**
 * A non-fatal problem (e.g. extractor missing, metadata timeout).
 */
warning: InspectionError | null, };
