// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormatPreset } from "./FormatPreset";
import type { VideoFormat } from "./VideoFormat";

export type VideoInfo = { id: string, title: string, thumbnail: string | null, durationSeconds: number | null, uploader: string | null, extractor: string | null, webpageUrl: string, isLive: boolean, formats: Array<VideoFormat>, presets: Array<FormatPreset>, ffmpegAvailable: boolean, };
