// Generates src-tauri/resources/THIRD-PARTY-NOTICES.md from the actual
// dependency graph (cargo metadata for the shipped binaries + npm production
// dependencies bundled into the UI). Run after changing dependencies.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const meta = JSON.parse(execFileSync("cargo", ["metadata", "--format-version", "1", "--locked"], { cwd: root, encoding: "utf8", maxBuffer: 256 * 1024 * 1024 }));

// Walk normal (non-dev, non-build) dependencies from the shipped packages.
const nodes = new Map(meta.resolve.nodes.map((n) => [n.id, n]));
const pkgs = new Map(meta.packages.map((p) => [p.id, p]));
const roots = meta.packages.filter((p) => ["pixidl", "pixidl-native-host"].includes(p.name)).map((p) => p.id);
const seen = new Set();
const stack = [...roots];
while (stack.length) {
  const id = stack.pop();
  if (seen.has(id)) continue;
  seen.add(id);
  for (const d of nodes.get(id)?.deps ?? []) {
    if (d.dep_kinds.some((k) => k.kind === null)) stack.push(d.pkg);
  }
}
const ours = new Set(["pixidl", "pixidl-native-host", "pixidl-core"]);
const crates = [...seen].map((id) => pkgs.get(id)).filter((p) => p && !ours.has(p.name));
crates.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));

const npmDeps = Object.keys(JSON.parse(readFileSync(join(root, "package.json"), "utf8")).dependencies ?? {});
const npm = npmDeps.sort().map((name) => {
  const pj = join(root, "node_modules", name, "package.json");
  const p = existsSync(pj) ? JSON.parse(readFileSync(pj, "utf8")) : {};
  return { name, version: p.version ?? "?", license: typeof p.license === "string" ? p.license : p.license?.type ?? "see package", repo: typeof p.repository === "string" ? p.repository : p.repository?.url ?? "" };
});

const lines = [
  "# Third-party notices",
  "",
  "pixidl is MIT licensed. It is built on the open-source software listed below;",
  "each component remains under its own license. This file is generated by `scripts/gen-notices.mjs`.",
  "",
  "## External engines",
  "",
  "- **yt-dlp** — The Unlicense (public domain). Bundled unmodified from the official release, checksum-verified at build time. https://github.com/yt-dlp/yt-dlp",
  "- **FFmpeg** — not bundled. If installed by the user it is used as an external program under its own license (LGPL/GPL). https://ffmpeg.org",
  "- **librqbit** (BitTorrent) — Apache-2.0. `librqbit-tracker-comms` is included with a small patch (see `third_party/README.md`). https://github.com/ikatson/rqbit",
  "- **Microsoft Edge WebView2** — provided by Windows / installed by the Microsoft bootstrapper under Microsoft's license.",
  "",
  `## Rust crates (${crates.length})`,
  "",
  "| Crate | Version | License |",
  "|---|---|---|",
  ...crates.map((c) => `| ${c.name} | ${c.version} | ${c.license ?? (c.license_file ? "see license file" : "unspecified")} |`),
  "",
  `## JavaScript packages bundled into the UI (${npm.length})`,
  "",
  "| Package | Version | License |",
  "|---|---|---|",
  ...npm.map((p) => `| ${p.name} | ${p.version} | ${p.license} |`),
  "",
  "Fonts: Inter (SIL Open Font License 1.1), Vazirmatn (SIL Open Font License 1.1).",
  "",
];
writeFileSync(join(root, "src-tauri", "resources", "THIRD-PARTY-NOTICES.md"), lines.join("\n"));
console.log(`notices: ${crates.length} crates, ${npm.length} npm packages`);
